---
title: "4a_DescStats for amphibian isolates"
output: html_notebook
---
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
#library(hrbrthemes)
library(viridis)
library(ggpubr)
#library(broom)
library(here)


## set directory and paths
here::here()
raw_dir <- here("data", "04_descStats", "04_raw")  ## raw output from programs like vs2, vibrant, checkv
out_dir <- here("data", "04_descStats", "04_out") ## output from R

```


```{r}
### if you don't want to run all the code below and just want the final tables for reference:
all.stats <- read.csv(here(out_dir, "SD_DescStats_dc068_ALL.csv"), row.names=1)
int.stats <- read.csv(here(out_dir, "SD_DescStats_dc068_Intact.csv"), row.names=1)
deg.stats <- read.csv(here(out_dir, "SD_DescStats_dc068_Deg.csv"), row.names=1)

IntDegFract <- read.csv(here(out_dir, "IntactDeg_Fraction.csv"), row.names=1)
AmphIsoCount <- read.csv(here(out_dir, "Amph_IsoCount.csv"))
```


```{r}
##subset out just amphibian phages for this portion of descriptive analysis
phage <- read.csv(here("data", "03_funcCleaning", "03_out","final_phagelist.csv"), row.names=1)
phage <- subset(phage, phage$Source=="Amphibian")
taxa <- read.csv(here("data", "00_metadata", "isolates_taxa.csv"))

### set tally to 0 if no phage was found

phage <- merge(phage, taxa, by="Genus", all.x=TRUE, all.y=FALSE)
phage.clean <- phage

```

```{r}
phage$tally <- ifelse(phage$phage_seq=="no_phage", 0, 1)


numphage.ag <- aggregate(phage[, c(30,12)], by=list(phage$Sequencing.ID, phage$Genus, phage$Family, phage$Order, phage$Class, phage$Phylum, phage$Bac.size), FUN=sum)

colnames(numphage.ag)[1:9] = c("iso_name","Genus", "Family", "Order", "Class", "Phylum", "bac.size", "Num_of_phage", "phage.length.sum" )
numphage.ag <- select(numphage.ag, Phylum, Class, Order, Family, Genus, iso_name, Num_of_phage, phage.length.sum, bac.size)

isolate.num = numphage.ag %>% group_by(Phylum) %>%  mutate(Phylum.size=n()) %>% group_by(Class) %>%  mutate(Class.size=n()) %>% group_by(Order) %>%  mutate(Order.size=n()) %>% group_by(Family) %>%  mutate(Family.size=n()) %>% group_by(Genus) %>%  mutate(Genus.size=n()) 

isolate.num <- aggregate(isolate.num[, 10:14], by=list(isolate.num$Phylum, isolate.num$Class, isolate.num$Order, isolate.num$Family, isolate.num$Genus), FUN=mean)

colnames(isolate.num)[1:5] = c("Phylum", "Class", "Order", "Family", "Genus")
#write.csv(isolate.num, here(out_dir, "Amph_IsoCount.csv"))

```

```{r}
##calculate phage percent

numphage.ag$percent <- numphage.ag$phage.length.sum/numphage.ag$bac.size*100

##calc min/max/median
MedPerc_numphage.ag <- aggregate(numphage.ag[, 10], by=list(numphage.ag$Genus), FUN=median)
colnames(MedPerc_numphage.ag)[1:2] = c("Genus", "Med_PhagePercent")

SDPerc_numphage.ag <- aggregate(numphage.ag[, 10], by=list(numphage.ag$Genus), FUN=sd)
colnames(SDPerc_numphage.ag)[1:2] = c("Genus", "SD_PhagePercent")

MinPerc_numphage.ag <- aggregate(numphage.ag[, 10], by=list(numphage.ag$Genus), FUN=min)
colnames(MinPerc_numphage.ag)[1:2] = c("Genus", "Min_PhagePercent")

MaxPerc_numphage.ag <- aggregate(numphage.ag[, 10], by=list(numphage.ag$Genus), FUN=max)
colnames(MaxPerc_numphage.ag)[1:2] = c("Genus", "Max_PhagePercent")


### calc min, median and max bac length
MinBacLength <- aggregate(numphage.ag[, 9], by=list(numphage.ag$Genus), FUN=min)
colnames(MinBacLength)[1:2] = c("Genus", "Min_BacterialGenome")

MaxBacLength <- aggregate(numphage.ag[, 9], by=list(numphage.ag$Genus), FUN=max)
colnames(MaxBacLength)[1:2] = c("Genus", "Max_BacterialGenome")

MedBacLength <- aggregate(numphage.ag[, 9], by=list(numphage.ag$Genus), FUN=median)

colnames(MedBacLength)[1:2] = c("Genus", "Median_BacterialGenome")

SdBacLength <- aggregate(numphage.ag[, 9], by=list(numphage.ag$Genus), FUN=sd)

colnames(SdBacLength)[1:2] = c("Genus", "Sd_baclength")
```


## Phage Lenth, Min/Max/Med ##
```{r}

##REMOVED all 0 samples so i could have just the smallest sized phage (instead of 0)

phage.pos <- subset(phage, phage$tally==1)
Min_phagelength.ag <- aggregate(phage.pos[, 12], by=list(phage.pos$Genus), FUN=min)

colnames(Min_phagelength.ag)[1:2] = c("Genus", "MinPhageLength")

Max_phagelength.ag <- aggregate(phage.pos[, 12], by=list(phage.pos$Genus), FUN=max)

colnames(Max_phagelength.ag)[1:2] = c("Genus", "MaxPhageLength")

Med_phagelength.ag <- aggregate(phage.pos[, 12], by=list(phage.pos$Genus), FUN=median)

colnames(Med_phagelength.ag)[1:2] = c("Genus", "MedianPhageLength")

SDphagelength_phage.ag <- aggregate(phage.pos[, 12], by=list(phage.pos$Genus), FUN=sd)

colnames(SDphagelength_phage.ag)[1:2] = c("Genus", "SD_PhageLength")
```


##Phage Num, Min/Max##
```{r}

Min_numphage.ag <- aggregate(numphage.ag[, 7], by=list(numphage.ag$Genus), FUN=min)

colnames(Min_numphage.ag)[1:2] = c("Genus", "MinNumPhage")

Max_numphage.ag <- aggregate(numphage.ag[, 7], by=list(numphage.ag$Genus), FUN=max)

colnames(Max_numphage.ag)[1:2] = c("Genus", "MaxNumPhage")

Med_numphage.ag <- aggregate(numphage.ag[, 7], by=list(numphage.ag$Genus), FUN=median)

colnames(Med_numphage.ag)[1:2] = c("Genus", "MedianNumPhage")

SD_numphage.ag <- aggregate(numphage.ag[, 7], by=list(numphage.ag$Genus), FUN=sd)

colnames(SD_numphage.ag)[1:2] = c("Genus", "SD_NumPhage")

```


```{r}

##need to reorder these, but merges all the group data (number, percent, size min/median/max) into one table
MergedDF <- merge(isolate.num, Min_numphage.ag, all=TRUE) %>%
          merge(Med_numphage.ag, all=TRUE) %>%  # num of phage
          merge(SD_numphage.ag, all=TRUE) %>%  
          merge(Max_numphage.ag, all=TRUE) %>%
            merge(MinPerc_numphage.ag, all=TRUE) %>% #phage percent
            merge(MedPerc_numphage.ag, all=TRUE) %>%
            merge(SDPerc_numphage.ag, all=TRUE) %>%
            merge(MaxPerc_numphage.ag, all=TRUE) %>%
                merge(Min_phagelength.ag, all=TRUE) %>% #phage length
                merge(Med_phagelength.ag, all=TRUE) %>%
                merge(SDphagelength_phage.ag, all=TRUE) %>%
                merge(Max_phagelength.ag, all=TRUE) %>%
                          merge(MinBacLength, all=TRUE) %>% #bac length
                          merge(MedBacLength, all=TRUE) %>% 
                          merge(SdBacLength, all=TRUE) %>% 
                          merge(MaxBacLength, all=TRUE) 
                    
      
MergedDF <- MergedDF[,c(2:5,1,6:26)]

#write.csv(MergedDF, here(out_dir, "SD_DescStats_dc068_ALL.csv"))

#write.csv(numphage.ag, here(out_dir, "Isolates_NumAll.csv"))

```



  
####INTACT ONLY #####

```{r}
phage <- phage.clean

phage$tally <- ifelse(phage$phage_seq=="no_phage" | phage$intact_est2=="Degraded", 0, 1)
## make all degraded phages have lengths of 0
phage$length.checkv <- ifelse(phage$phage_seq=="no_phage" | phage$intact_est2=="Degraded", 0, phage$length.checkv)

numphage.ag <- aggregate(phage[, c(30,12)], by=list(phage$Sequencing.ID, phage$Genus, phage$Family, phage$Order, phage$Class, phage$Phylum, phage$Bac.size), FUN=sum)

colnames(numphage.ag)[1:9] = c("iso_name","Genus", "Family", "Order", "Class", "Phylum", "bac.size", "Num_of_phage", "phage.length.sum" )
numphage.ag <- select(numphage.ag, Phylum, Class, Order, Family, Genus, iso_name, Num_of_phage, phage.length.sum, bac.size)

```

```{r}
##calculate phage percent

numphage.ag$percent <- numphage.ag$phage.length.sum/numphage.ag$bac.size*100

##calc min/max/median
MedPerc_numphage.ag <- aggregate(numphage.ag[, 10], by=list(numphage.ag$Genus), FUN=median)
colnames(MedPerc_numphage.ag)[1:2] = c("Genus", "Med_PhagePercent")

SDPerc_numphage.ag <- aggregate(numphage.ag[, 10], by=list(numphage.ag$Genus), FUN=sd)
colnames(SDPerc_numphage.ag)[1:2] = c("Genus", "SD_PhagePercent")

MinPerc_numphage.ag <- aggregate(numphage.ag[, 10], by=list(numphage.ag$Genus), FUN=min)
colnames(MinPerc_numphage.ag)[1:2] = c("Genus", "Min_PhagePercent")

MaxPerc_numphage.ag <- aggregate(numphage.ag[, 10], by=list(numphage.ag$Genus), FUN=max)
colnames(MaxPerc_numphage.ag)[1:2] = c("Genus", "Max_PhagePercent")


### calc min, median and max bac length
MinBacLength <- aggregate(numphage.ag[, 9], by=list(numphage.ag$Genus), FUN=min)
colnames(MinBacLength)[1:2] = c("Genus", "Min_BacterialGenome")

MaxBacLength <- aggregate(numphage.ag[, 9], by=list(numphage.ag$Genus), FUN=max)
colnames(MaxBacLength)[1:2] = c("Genus", "Max_BacterialGenome")

MedBacLength <- aggregate(numphage.ag[, 9], by=list(numphage.ag$Genus), FUN=median)

colnames(MedBacLength)[1:2] = c("Genus", "Median_BacterialGenome")

SdBacLength <- aggregate(numphage.ag[, 9], by=list(numphage.ag$Genus), FUN=sd)

colnames(SdBacLength)[1:2] = c("Genus", "Sd_baclength")
```


## Phage Lenth, Min/Max/Med ##
```{r}

##REMOVED all 0 samples so i could have just the smallest sized phage (instead of 0)

phage.pos <- subset(phage, phage$tally==1)
Min_phagelength.ag <- aggregate(phage.pos[, 12], by=list(phage.pos$Genus), FUN=min)

colnames(Min_phagelength.ag)[1:2] = c("Genus", "MinPhageLength")

Max_phagelength.ag <- aggregate(phage.pos[, 12], by=list(phage.pos$Genus), FUN=max)

colnames(Max_phagelength.ag)[1:2] = c("Genus", "MaxPhageLength")

Med_phagelength.ag <- aggregate(phage.pos[, 12], by=list(phage.pos$Genus), FUN=median)

colnames(Med_phagelength.ag)[1:2] = c("Genus", "MedianPhageLength")

SDphagelength_phage.ag <- aggregate(phage.pos[, 12], by=list(phage.pos$Genus), FUN=sd)

colnames(SDphagelength_phage.ag)[1:2] = c("Genus", "SD_PhageLength")
```


##Phage Num, Min/Max##
```{r}

Min_numphage.ag <- aggregate(numphage.ag[, 7], by=list(numphage.ag$Genus), FUN=min)

colnames(Min_numphage.ag)[1:2] = c("Genus", "MinNumPhage")

Max_numphage.ag <- aggregate(numphage.ag[, 7], by=list(numphage.ag$Genus), FUN=max)

colnames(Max_numphage.ag)[1:2] = c("Genus", "MaxNumPhage")

Med_numphage.ag <- aggregate(numphage.ag[, 7], by=list(numphage.ag$Genus), FUN=median)

colnames(Med_numphage.ag)[1:2] = c("Genus", "MedianNumPhage")

SD_numphage.ag <- aggregate(numphage.ag[, 7], by=list(numphage.ag$Genus), FUN=sd)

colnames(SD_numphage.ag)[1:2] = c("Genus", "SD_NumPhage")

```


```{r}

##need to reorder these, but merges all the group data (number, percent, size min/median/max) into one table
MergedDF <- merge(isolate.num, Min_numphage.ag, all=TRUE) %>%
          merge(Med_numphage.ag, all=TRUE) %>%  # num of phage
          merge(SD_numphage.ag, all=TRUE) %>%  
          merge(Max_numphage.ag, all=TRUE) %>%
            merge(MinPerc_numphage.ag, all=TRUE) %>% #phage percent
            merge(MedPerc_numphage.ag, all=TRUE) %>%
            merge(SDPerc_numphage.ag, all=TRUE) %>%
            merge(MaxPerc_numphage.ag, all=TRUE) %>%
                merge(Min_phagelength.ag, all=TRUE) %>% #phage length
                merge(Med_phagelength.ag, all=TRUE) %>%
                merge(SDphagelength_phage.ag, all=TRUE) %>%
                merge(Max_phagelength.ag, all=TRUE) %>%
                          merge(MinBacLength, all=TRUE) %>% #bac length
                          merge(MedBacLength, all=TRUE) %>% 
                          merge(SdBacLength, all=TRUE) %>% 
                          merge(MaxBacLength, all=TRUE) 
                    
      
MergedDF <- MergedDF[,c(2:5,1,6:26)]

#write.csv(MergedDF, here(out_dir, "SD_DescStats_dc068_Intact.csv"))
#write.csv(numphage.ag, here(out_dir, "Isolates_NumIntact.csv"))

```
####DEGRADED ONLY #####

```{r}
phage <- phage.clean


phage$tally <- ifelse(phage$phage_seq=="no_phage" | phage$intact_est2=="Intact", 0, 1)
phage$length.checkv <- ifelse(phage$phage_seq=="no_phage" | phage$intact_est2=="Intact", 0, phage$length.checkv)

numphage.ag <- aggregate(phage[, c(30,12)], by=list(phage$Sequencing.ID, phage$Genus, phage$Family, phage$Order, phage$Class, phage$Phylum, phage$Bac.size), FUN=sum)

colnames(numphage.ag)[1:9] = c("iso_name","Genus", "Family", "Order", "Class", "Phylum", "bac.size", "Num_of_phage", "phage.length.sum" )
numphage.ag <- select(numphage.ag, Phylum, Class, Order, Family, Genus, iso_name, Num_of_phage, phage.length.sum, bac.size)

```

```{r}
##calculate phage percent

numphage.ag$percent <- numphage.ag$phage.length.sum/numphage.ag$bac.size*100

##calc min/max/median
MedPerc_numphage.ag <- aggregate(numphage.ag[, 10], by=list(numphage.ag$Genus), FUN=median)
colnames(MedPerc_numphage.ag)[1:2] = c("Genus", "Med_PhagePercent")

SDPerc_numphage.ag <- aggregate(numphage.ag[, 10], by=list(numphage.ag$Genus), FUN=sd)
colnames(SDPerc_numphage.ag)[1:2] = c("Genus", "SD_PhagePercent")

MinPerc_numphage.ag <- aggregate(numphage.ag[, 10], by=list(numphage.ag$Genus), FUN=min)
colnames(MinPerc_numphage.ag)[1:2] = c("Genus", "Min_PhagePercent")

MaxPerc_numphage.ag <- aggregate(numphage.ag[, 10], by=list(numphage.ag$Genus), FUN=max)
colnames(MaxPerc_numphage.ag)[1:2] = c("Genus", "Max_PhagePercent")


### calc min, median and max bac length
MinBacLength <- aggregate(numphage.ag[, 9], by=list(numphage.ag$Genus), FUN=min)
colnames(MinBacLength)[1:2] = c("Genus", "Min_BacterialGenome")

MaxBacLength <- aggregate(numphage.ag[, 9], by=list(numphage.ag$Genus), FUN=max)
colnames(MaxBacLength)[1:2] = c("Genus", "Max_BacterialGenome")

MedBacLength <- aggregate(numphage.ag[, 9], by=list(numphage.ag$Genus), FUN=median)

colnames(MedBacLength)[1:2] = c("Genus", "Median_BacterialGenome")

SdBacLength <- aggregate(numphage.ag[, 9], by=list(numphage.ag$Genus), FUN=sd)

colnames(SdBacLength)[1:2] = c("Genus", "Sd_baclength")
```


## Phage Lenth, Min/Max/Med ##
```{r}

##REMOVED all 0 samples so i could have just the smallest sized phage (instead of 0)

phage.pos <- subset(phage, phage$tally==1)
Min_phagelength.ag <- aggregate(phage.pos[, 12], by=list(phage.pos$Genus), FUN=min)

colnames(Min_phagelength.ag)[1:2] = c("Genus", "MinPhageLength")

Max_phagelength.ag <- aggregate(phage.pos[, 12], by=list(phage.pos$Genus), FUN=max)

colnames(Max_phagelength.ag)[1:2] = c("Genus", "MaxPhageLength")

Med_phagelength.ag <- aggregate(phage.pos[, 12], by=list(phage.pos$Genus), FUN=median)

colnames(Med_phagelength.ag)[1:2] = c("Genus", "MedianPhageLength")

SDphagelength_phage.ag <- aggregate(phage.pos[, 12], by=list(phage.pos$Genus), FUN=sd)

colnames(SDphagelength_phage.ag)[1:2] = c("Genus", "SD_PhageLength")
```


##Phage Num, Min/Max##
```{r}

Min_numphage.ag <- aggregate(numphage.ag[, 7], by=list(numphage.ag$Genus), FUN=min)

colnames(Min_numphage.ag)[1:2] = c("Genus", "MinNumPhage")

Max_numphage.ag <- aggregate(numphage.ag[, 7], by=list(numphage.ag$Genus), FUN=max)

colnames(Max_numphage.ag)[1:2] = c("Genus", "MaxNumPhage")

Med_numphage.ag <- aggregate(numphage.ag[, 7], by=list(numphage.ag$Genus), FUN=median)

colnames(Med_numphage.ag)[1:2] = c("Genus", "MedianNumPhage")

SD_numphage.ag <- aggregate(numphage.ag[, 7], by=list(numphage.ag$Genus), FUN=sd)

colnames(SD_numphage.ag)[1:2] = c("Genus", "SD_NumPhage")

```


```{r}

##need to reorder these, but merges all the group data (number, percent, size min/median/max) into one table
MergedDF <- merge(isolate.num, Min_numphage.ag, all=TRUE) %>%
          merge(Med_numphage.ag, all=TRUE) %>%  # num of phage
          merge(SD_numphage.ag, all=TRUE) %>%  
          merge(Max_numphage.ag, all=TRUE) %>%
            merge(MinPerc_numphage.ag, all=TRUE) %>% #phage percent
            merge(MedPerc_numphage.ag, all=TRUE) %>%
            merge(SDPerc_numphage.ag, all=TRUE) %>%
            merge(MaxPerc_numphage.ag, all=TRUE) %>%
                merge(Min_phagelength.ag, all=TRUE) %>% #phage length
                merge(Med_phagelength.ag, all=TRUE) %>%
                merge(SDphagelength_phage.ag, all=TRUE) %>%
                merge(Max_phagelength.ag, all=TRUE) %>%
                          merge(MinBacLength, all=TRUE) %>% #bac length
                          merge(MedBacLength, all=TRUE) %>% 
                          merge(SdBacLength, all=TRUE) %>% 
                          merge(MaxBacLength, all=TRUE) 
                    
      
MergedDF <- MergedDF[,c(2:5,1,6:26)]

#write.csv(MergedDF, here(out_dir, "SD_DescStats_dc068_Deg.csv"))

#write.csv(numphage.ag, here(out_dir, "Isolates_NumDeg.csv"))
```


```{r}

Int <- select(phage, phage_seq, Sequencing.ID, Genus, intact_est2) 
Int$int.present <- 0
Int$int.present <- ifelse(Int$intact_est2=="Intact", 1, 0)
Int$deg.present <- ifelse(Int$intact_est2=="Degraded", 1, 0)
Int <- aggregate(Int[c(5,6)], by=list(Int$Genus, Int$Sequencing.ID), FUN=max)
Int <- aggregate(Int[c(3,4)], by=list(Int$Group.1), FUN=sum)


colnames(Int)[1:3] = c("Genus","Num_Isolates_with_Intact", "Num_Isolates_With_Degraded")

iso.num <- read.csv(here(out_dir, "Amph_IsoCount.csv"), row.names=1)
iso.num <- iso.num[,c(5,10)]

IntFract <- merge(iso.num, Int, by="Genus", all=TRUE)
IntFract$PercentIntGenome <- IntFract$Num_Isolates_with_Intact/IntFract$Genus.size*100
IntFract$PercentDegGenome <- IntFract$Num_Isolates_With_Degraded/IntFract$Genus.size*100



#write.csv(IntFract, here(out_dir, "IntactDeg_Fraction.csv"))


```
