---
title: "5b_distrbution graphs of Janthino"
output: html_notebook
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
#library(hrbrthemes)
library(ggpubr)
library(tidyverse)
library(cowplot)
library(PNWColors)
library(here)

here::here()

fig_dir <- here("figs") 
supp_dir <- here("figs", "supp") 



pal2=pnw_palette("Sailboat",7, type = "continuous")


theme_set(theme_classic(base_family = "sans"))
 
vertheme <- theme_bw()+theme( 
      legend.position="none", 
      plot.title = element_text(size=15),
      axis.text.x = element_text(size= 15, angle=0, vjust=0.5),
      axis.text.y = element_text(size=15),
      axis.title.y = element_text(size=15),
      axis.title.x = element_text(size=15),
      axis.ticks.length = unit(.3, "cm")
    ) 


```

```{r}

all.stats <- read.csv(here("data", "04_descStats", "04_out", "Isolates_NumAllJanthino.csv"), row.names=1)

int.stats <- read.csv(here("data", "04_descStats", "04_out", "Isolates_NumIntJanthino.csv"), row.names=1)

int.stats <- int.stats[,c(1,6,8)]
colnames(int.stats)[2:3] = c("NumIntPhage", "PercIntPhage")


phage <- merge(all.stats, int.stats, by="iso_name", all=TRUE)
phage[is.na(phage)] <- 0
phage$tax_f <- phage$Family
phage$Family <- NULL

phage$IntBin_VLP3 <- ifelse(phage$NumIntPhage>0, "One or More Intact Prophage", "No Intact Prophage")

#phage <- merge(phage, bd, by="iso_name", all.x=TRUE, all.y=FALSE)

phage$NumCryp <- phage$Num_of_phage - phage$NumIntPhage
#phage$PercCryp <- phage$percent - phage$IntPerc
phage$PercCryp <- 0

phage$PercCryp <- ifelse(round(phage$percent, 2)==round(phage$PercIntPhage,2), 0, phage$percent-phage$PercIntPhage)


phage2 <- select(phage, iso_name, Isolation, NumCryp, PercCryp, NumIntPhage, PercIntPhage, bac.size)

phage2$Isolation <- ifelse(phage2$Isolation=="Enviro", "Environment", phage2$Isolation)
phage2$Isolation<- ifelse(phage2$Isolation=="Host_non", "Host (other)", phage2$Isolation)
phage2$Isolation <- ifelse(phage2$Isolation=="Amphibian", "Amphibian Host", phage2$Isolation)


colnames(phage2)[3:6] = c("B. Degraded Prophage", "B. Degraded Prophage Composition", "A. Intact Prophage", "A. Intact Prophage Composition")

phage.long <- phage2 %>%
  pivot_longer(
    cols = c("B. Degraded Prophage", "B. Degraded Prophage Composition", "A. Intact Prophage", "A. Intact Prophage Composition"),
    names_to = "Type", 
    values_to = "Number",
    values_drop_na = TRUE
  )


phage.num <- phage2[,c(1,2,3,5)]
phage.perc <- phage2[,c(1,2,4,6)]
phage.num <- phage.num %>%
  pivot_longer(
    cols = c("A. Intact Prophage", "B. Degraded Prophage"), 
    names_to = "Type", 
    values_to = "Number",
    values_drop_na = TRUE
  )

phage.perc <- phage.perc %>%
  pivot_longer(
    cols = c("A. Intact Prophage Composition", "B. Degraded Prophage Composition"), 
    names_to = "Type", 
    values_to = "Percent",
    values_drop_na = TRUE
  )


```

```{r}

### BF kruskal test of how isolation source impacts prophage distribution
pvals <- c(
  kruskal.test(phage$Num_of_phage ~ phage$Isolation)$p.value,
  kruskal.test(phage$percent ~ phage$Isolation)$p.value,
  kruskal.test(phage$PercIntPhage ~ phage$Isolation)$p.value,
  kruskal.test(phage$NumIntPhage ~ phage$Isolation)$p.value,
  kruskal.test(phage$NumCryp ~ phage$Isolation)$p.value,
  kruskal.test(phage$PercCryp ~ phage$Isolation)$p.value
)
#"A. Intact Prophage", "B. Degraded Prophage"
tests <- c("Num_of_phage", "percent", "A. Intact Prophage Composition", "A. Intact Prophage", "B. Degraded Prophage", "B. Degraded Prophage Composition")

# Build data frame with raw and adjusted p-values
pvals_df <- data.frame(
  Test = tests,
  P_value = pvals,
  Adj_P_value = p.adjust(pvals, method = "BH")
)

# Build data frame with raw and adjusted p-values
pvals_df <- data.frame(
  Test = tests,
  P_value = pvals,
  Adj_P_value = p.adjust(pvals, method = "BH")
)

facet_labels <- pvals_df |>
  mutate(Type = Test,
         label = paste0("p = ", signif(Adj_P_value, 1)),
         x = 1, y = 6.5)


num_labels <- subset(facet_labels, facet_labels$Test=="A. Intact Prophage" |  facet_labels$Test=="B. Degraded Prophage")

perc_labels <- subset(facet_labels, facet_labels$Test=="A. Intact Prophage Composition" |  facet_labels$Test=="B. Degraded Prophage Composition")


```

```{r}




num_phage <- ggplot(phage.num, aes(x = Isolation, y = Number, fill=Isolation  )) + geom_boxplot(outlier.size = 0) +scale_fill_manual(values=pal2) +  geom_point(pch = 21, size= 2.25, position=position_dodge2(width=.5)) + scale_y_continuous(limits=c(0, 5), breaks=seq(0,5,1)) + ylab("Predicted Prophage") + xlab("Isolation Source") + vertheme + coord_flip()+facet_wrap(~ Type, ncol = 2)+ theme(strip.text = element_text(size = 15))

num_phage <- num_phage +
  geom_text(
    data = num_labels,
    aes(x = 0.5, y = 4.5, label = label),
    inherit.aes = FALSE,
    size = 5
  )

num_phage
## save gg image to be used in composite figure later (see 09_.rmd)
saveRDS(num_phage, file="data/05_distribGraphs/05_out/janthino_numphage.RDS")
```


```{r}
perc_phage <- ggplot(phage.perc, aes(x = Isolation, y = Percent, fill=Isolation  )) + geom_boxplot(outlier.size = 0) +scale_fill_manual(values=pal2) +  geom_point(pch = 21, size= 2.25, position=position_dodge2(width=.5)) + scale_y_continuous(limits=c(0, 5), breaks=seq(0,5,1)) + ylab("Prophage Composition") +xlab("Isolation Source") +vertheme  + coord_flip()+facet_wrap(~ Type, ncol = 2)+ theme(strip.text = element_text(size = 15))



perc_phage <- perc_phage +
  geom_text(
    data = perc_labels,
    aes(x = 0.5, y = 4.5, label = label),
    inherit.aes = FALSE,
    size = 5
  )

perc_phage
ggsave(here(supp_dir, "S2.pdf"), width=11, height=8)
ggsave(here(supp_dir, "S2.png"), width=11, height=8)
```



